site_name: CTF Reports
site_url: https://<your-user>.github.io/ctf-reports/
repo_name: <your-user>/ctf-reports
repo_url: https://github.com/<your-user>/ctf-reports
theme:
  name: material
  language: vi
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Trang chủ: index.md
  - 2025:
      - NNSCTF:
          - devsecoops: 2025/nnsctf/devsecoops/README.md
